# Generated by Django 5.2.5 on 2025-08-16 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('bhk', models.IntegerField(blank=True, null=True)),
                ('property_type', models.CharField(blank=True, max_length=100, null=True)),
                ('developer', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.CharField(blank=True, max_length=255, null=True)),
                ('floor_current', models.IntegerField(blank=True, null=True)),
                ('floor_total', models.IntegerField(blank=True, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=50, null=True)),
                ('facing', models.CharField(blank=True, max_length=50, null=True)),
                ('furnished_status', models.CharField(blank=True, max_length=50, null=True)),
                ('ownership_type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('locality', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('super_built_up_area', models.FloatField(blank=True, null=True)),
                ('carpet_area', models.FloatField(blank=True, null=True)),
                ('total_area', models.FloatField(blank=True, null=True)),
                ('price_per_sqft', models.FloatField(blank=True, null=True)),
                ('price_in_inr', models.FloatField(blank=True, null=True)),
                ('property_yield', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('parking_count', models.IntegerField(blank=True, null=True)),
                ('parking_type', models.CharField(blank=True, max_length=50, null=True)),
                ('property_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalityRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectivity', models.FloatField(blank=True, null=True)),
                ('safety', models.FloatField(blank=True, null=True)),
                ('traffic', models.FloatField(blank=True, null=True)),
                ('environment', models.FloatField(blank=True, null=True)),
                ('market', models.FloatField(blank=True, null=True)),
                ('area_description', models.TextField(blank=True, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locality_rating', to='propalyze.property')),
            ],
        ),
        migrations.CreateModel(
            name='LocalityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locality_photos', to='propalyze.property')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_prices', to='propalyze.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='propalyze.property')),
            ],
        ),
        migrations.CreateModel(
            name='SavedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='propalyze.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
